spring:
  application:
    name: wallet-service
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platfrom: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
server:
  port: 8083

eureka:
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka
  instance:
    preferIpAddress: true

