spring:
  application:
    name: Gateway
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

zuul:
  ignoredServices: '*'
  routes:
    wallets:
      path: '/wallet/**'
      stripPrefix: false
      serviceId: 'http://localhost:8083/'
    games:
      path: '/game/**'
      stripPefix: false
      serviceId: 'http://localhost:8084/'