spring:
  application:
    name: Gateway
server:
  port: 8080

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

zuul:
  ribbon:
    eager-load:
      enabled: true
    connectTimeout: 10000
    readTimeout: 10000
  ignoredServices: '*'
  routes:
    games:
      path: '/game/**'
      strip-prefix: false
      service-id: 'game'
    wallets:
      path: '/wallet/**'
      strip-prefix: false
      service-id: 'wallet'


logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace

hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: false