spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: game-service
          uri: lb://game-service
          predicates:
            - Path=/game/**
        - id: wallet-service
          uri: lb://wallet-service
          stripPrefix: false
          predicates:
            - Path=/wallet/**

server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka