spring:
  application:
    name: gateway-service
server:
  port: 8080

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

ribbon:
  http:
    client:
      enabled: false
  restclient:
    enabled: false

zuul:
  host:
    eager-load:
      enabled: true
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
    max-total-connections: 1000
    max-per-route-connections: 50
  ignoredServices: '*'
  routes:
    game-service:
      path: /game/**
      stripPrefix: false
      serviceId: game-service
      ribbon:
        listOfServers: http://localhost:8081
    wallet-service:
      path: /wallet/**
      strip-prefix: false
      service-id: wallet-service
      ribbon:
        listOfServers: http://localhost:8081

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace