spring:
  application:
    name: Gateway
server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka

zuul:
  ignoredServices: '*'
  routes:
    games:
      path: /game/**
      strip-prefix: false
      service-id: game
    wallets:
      path: /wallet/**
      strip-prefix: false
      service-id: wallet

logging:
  level:
    org:
      springframework:
        cloud:
          netflix: trace